export enum ClothesCategory {
    ALL = '',
    DRESSES = 'dresses',
    DENIM = 'denim',
    JEANS = 'jeans',
    JUMPSUITS = 'jumpsuits',
    TOPS = 'tops',
    JACKETS_AND_COATS = 'jackets_and_coats',
    PANTS = 'pants',
    SHORTS = 'shorts',
    SKIRTS = 'skirts',
    LOUNGERIE_AND_UNDERWEAR = 'loungerie_and_underwear',
    LEATHER = 'leather',
    SWEATERS_AND_KNITS = 'sweaters_and_knits',
}

export enum ClothesCategoryLabel {
    ALL = 'All',
    DRESSES = 'Dresses',
    DENIM = 'Denim',
    JEANS = 'Jeans',
    JUMPSUITS = 'Jumpsuits',
    TOPS = 'Tops',
    JACKETS_AND_COATS = 'Jackets and coats',
    PANTS = 'Pants',
    SHORTS = 'Shorts',
    SKIRTS = 'Skirts',
    LOUNGERIE_AND_UNDERWEAR = 'Loungerie & underwear',
    LEATHER = 'Leather',
    SWEATERS_AND_KNITS = 'Sweaters & knits',
}

export enum ShoesCategory {
    ALL = '',
    BOOTIES = 'booties',
    FLATS = 'flats',
    BOOTS = 'boots',
    SANDALS = 'sandals',
    SNEAKERS = 'sneakers',
    SLIDE_AND_SLIPPERS = 'slide_and_slippers',
    HEELS = 'heels',
    WEDGES = 'wedges',
    MULES = 'mules',
    PARTY_SHOES = 'party_shoes',
    VEGAN_SHOES = 'vegan_shoes',
    OXFORDS = 'oxfords'
}

export enum ShoesCategoryLabel {
    ALL = 'All',
    BOOTIES = 'Booties',
    FLATS = 'Flats',
    BOOTS = 'Boots',
    SANDALS = 'Sandals',
    SNEAKERS = 'Sneakers',
    SLIDE_AND_SLIPPERS = 'Slide & slippers',
    HEELS = 'Heels',
    WEDGES = 'Wedges',
    MULES = 'Mules',
    PARTY_SHOES = 'Party shoes',
    VEGAN_SHOES = 'Vegan shoes',
    OXFORDS = 'Oxfords'
}

export enum AccessoriesCategory {
    ALL = '',
    FACEMASK = 'facemask',
    JEWELRY = 'jewelry',
    WATCHES = 'watches',
    HAIR_ACCESSORIES = 'hair_accessories',
    BELTS = 'belts',
    BACKPACKS = 'backpacks',
    HANDBAGS = 'handbags',
    FRAGRANCES = 'fragrances',
    SUNGLASSES_AND_EYEWEARS = 'sunglasses_and_eyewears',
    SOCKS = 'socks',
    HATS_AND_BEANIES = 'hats_and_beans',
    GLOVES = 'gloves'
}

export enum AccessoriesCategoryLabel {
    ALL = 'All',
    FACEMASK = 'Facemask',
    JEWELRY = 'Jewelry',
    WATCHES = 'Watches',
    HAIR_ACCESSORIES = 'Hair accessories',
    BELTS = 'Belts',
    BACKPACKS = 'Backpacks',
    HANDBAGS = 'Handbags',
    FRAGRANCES = 'Fragrances',
    SUNGLASSES_AND_EYEWEARS = 'Sunglasses & eyewears',
    SOCKS = 'Socks',
    HATS_AND_BEANIES = 'Hats and beanies',
    GLOVES = 'Gloves'
}

export enum ProductCategory {
    ALL = '',
    FACEMASK = 'facemask',
    JEWELRY = 'jewelry',
    WATCHES = 'watches',
    HAIR_ACCESSORIES = 'hair_accessories',
    BELTS = 'belts',
    BACKPACKS = 'backpacks',
    HANDBAGS = 'handbags',
    FRAGRANCES = 'fragrances',
    SUNGLASSES_AND_EYEWEARS = 'sunglasses_and_eyewears',
    SOCKS = 'socks',
    HATS_AND_BEANIES = 'hats_and_beans',
    GLOVES = 'gloves',
    BOOTIES = 'booties',
    FLATS = 'flats',
    BOOTS = 'boots',
    SANDALS = 'sandals',
    SNEAKERS = 'sneakers',
    SLIDE_AND_SLIPPERS = 'slide_and_slippers',
    HEELS = 'heels',
    WEDGES = 'wedges',
    MULES = 'mules',
    PARTY_SHOES = 'party_shoes',
    VEGAN_SHOES = 'vegan_shoes',
    OXFORDS = 'oxfords',
    DRESSES = 'dresses',
    DENIM = 'denim',
    JEANS = 'jeans',
    JUMPSUITS = 'jumpsuits',
    TOPS = 'tops',
    JACKETS_AND_COATS = 'jackets_and_coats',
    PANTS = 'pants',
    SHORTS = 'shorts',
    SKIRTS = 'skirts',
    LOUNGERIE_AND_UNDERWEAR = 'loungerie_and_underwear',
    LEATHER = 'leather',
    SWEATERS_AND_KNITS = 'sweaters_and_knits',
}

export enum ProductCategoryLabel {
    ALL = 'All',
    FACEMASK = 'Facemask',
    JEWELRY = 'Jewelry',
    WATCHES = 'Watches',
    HAIR_ACCESSORIES = 'Hair accessories',
    BELTS = 'Belts',
    BACKPACKS = 'Backpacks',
    HANDBAGS = 'Handbags',
    FRAGRANCES = 'Fragrances',
    SUNGLASSES_AND_EYEWEARS = 'Sunglasses & eyewears',
    SOCKS = 'Socks',
    HATS_AND_BEANIES = 'Hats and beanies',
    GLOVES = 'Gloves',
    BOOTIES = 'Booties',
    FLATS = 'Flats',
    BOOTS = 'Boots',
    SANDALS = 'Sandals',
    SNEAKERS = 'Sneakers',
    SLIDE_AND_SLIPPERS = 'Slide & slippers',
    HEELS = 'Heels',
    WEDGES = 'Wedges',
    MULES = 'Mules',
    PARTY_SHOES = 'Party shoes',
    VEGAN_SHOES = 'Vegan shoes',
    OXFORDS = 'Oxfords',
    DRESSES = 'Dresses',
    DENIM = 'Denim',
    JEANS = 'Jeans',
    JUMPSUITS = 'Jumpsuits',
    TOPS = 'Tops',
    JACKETS_AND_COATS = 'Jackets and coats',
    PANTS = 'Pants',
    SHORTS = 'Shorts',
    SKIRTS = 'Skirts',
    LOUNGERIE_AND_UNDERWEAR = 'Loungerie & underwear',
    LEATHER = 'Leather',
    SWEATERS_AND_KNITS = 'Sweaters & knits',
}